### ISSUE TITLE
No background customizing option

### ISSUE THREAD

**Issue by DiamondRivlz** [Paturages/chorus#108]
Hey, so after April Fool's you added an option to customize the background, pretty cool. But since the site's last update, there's no way to change the background anymore (although the one I used before is still there).

Are you planning on taking out that feature? Please don't, I like it.

**Comment by Paturages** [comment]
@tonybaroneee wanna add it back?

**Comment by tonybaroneee** [comment]
Not to worry Diamond, we’ll add this right back in :) Thanks for the feedback!

**Comment by tonybaroneee** [comment]
@DiamondRivlz You can change the background again via the "Set Background" link in the top-right :)

![image](https://user-images.githubusercontent.com/844249/39522045-047b78be-4ddf-11e8-8484-94ecbdfbfe75.png)

Enjoy!
