### ISSUE TITLE
band and song search issue

### ISSUE THREAD

**Issue by ixishadesixi** [Paturages/chorus#116]
I've noticed just recently when you search for a band and you get through the first page of songs and click on more songs it doesn't show more from the band rather shows Bloodhound gang, ewan dobson etc etc. Never had this issue before, just a heads up.

**Comment by tonybaroneee** [comment]
Thanks for the report, will take a look later today. Expect a fix soon!

**Comment by ixishadesixi** [comment]
Appreciate it!

**Comment by tonybaroneee** [comment]
All set! Refresh for the fix :)

**Comment by ixishadesixi** [comment]
That was fast, thanks!
