### ISSUE TITLE
Add advanced search

### ISSUE THREAD

**Issue by Paturages** [Paturages/chorus#12]

**Comment by Tetrinity** [comment]
Looking forward to this. The current search behaviour seems somewhat odd; for example searching for "Nile" first lists a couple of Exilelord songs, then a couple of actual Nile songs, then devolves into apparently random entries, despite other Nile songs existing in the directory if you know what to search for! Felt silly to raise it as a separate issue when it's being reworked anyway, though...

**Comment by Paturages** [comment]
The way I quick search isn't so good with short queries indeed... People looking for particular artists (and know how to spell) should have less trouble with advanced queries.

Anyway, d0b75ad8680c8fa5545bac78afd3e4644afa994a introduces a first version of advanced search, I'll progressively tweak it as I go.
