### ISSUE TITLE
Missing guitar.ogg

### ISSUE THREAD

**Issue by MaxOnBass** [Paturages/chorus#130]
Hello,

I send this message to report a problem with the songs Moonrise by L-Train (and friends). They do not work on Clone Hero because the file guitar.ogg is missing. And the problem is for all the titles of the song (Harmony, Prelude....).

Hope it'll be fixe very soon.

Best regards.

**Comment by Paturages** [comment]
This is an issue with the charts that are hosted on the "C3 conversions" drive, I'll forward it to CaGe666#6995 who is in charge of it. Thanks for the report.

**Comment by Paturages** [comment]
Issue closed due to the fact that C3 conversions aren't up anymore.
