### ISSUE TITLE
Why does not this work for me?

### ISSUE THREAD

**Issue by Duknine2** [Paturages/chorus#139]
I already left the link of my G.Drive in public, but when searching for my nickname in the lobby of the Chorus or at least the songs that I created, none appears.

I'd like someone to respond instead of deleting my topics, that's chit.

**Comment by Paturages** [comment]
It's not synchronized yet, you gotta wait until it synchronizes again in approximately 12 hours. Sorry if the previous issue was closed, it was automatically triggered by the modifications I made to fix the sources.

**Comment by Paturages** [comment]
[This should be it](https://chorus.fightthe.pw/search?query=charter%3D"duknine")

**Comment by Duknine2** [comment]
Thank you! i'm glad it worked.
