### ISSUE TITLE
song

### ISSUE THREAD

**Issue by rmzncnsmsk** [Paturages/chorus#173]
Metallica - St. Anger have notes but any sound in the game please check and fix thank u :)

**Comment by Paturages** [comment]
This is an issue with the charts that are hosted on the "C3 conversions" drive, I'll forward it to CaGe666#6995 who is in charge of it. Thanks for the report.

[Link to affected Google Drive download page](https://drive.google.com/drive/folders/0B1lvPFfHBT2LWTRUdEhsc0xIRnM)

**Comment by Lutarisco** [comment]
The same happens with The Cardigans - Lovefool (I hope this belongs here). Thanks. I appreciate your work guys!

**Comment by Paturages** [comment]
Issue closed due to the fact that C3 conversions aren't up anymore.
