### ISSUE TITLE
Harmonix's charts won't download..

### ISSUE THREAD

**Issue by ShadowStriker2** [Paturages/chorus#177]
When i try to download Harmonix's charts, they won't download at all. When i download other charter's charts, they download with no problems.

**Comment by Paturages** [comment]
Can you specify some examples in particular?

**Comment by ShadowStriker2** [comment]
Every chart, which is made by Harmonix won't download

**Comment by Paturages** [comment]
Is this still happening? I literally have no idea why it'd happen and I've only really heard it here from you :/

**Comment by ShadowStriker2** [comment]
Not happening anymore, i cleared my browser's history and it seemed to fix the problem :D

**Comment by Paturages** [comment]
Good to know!
