### ISSUE TITLE
No copyright license

### ISSUE THREAD

**Issue by shockdude** [Paturages/chorus#192]
Could you please [add a license](https://docs.npmjs.com/files/package.json#license) to chorus?
The current [package.json](https://github.com/Paturages/chorus/blob/master/package.json) says the license is ISC, but doesn't include a copy of the [ISC license](https://en.wikipedia.org/wiki/ISC_license).
[Not having a license](https://choosealicense.com/no-permission/) legally means nobody else can mirror chorus, or even use chorus, without risking litigation from you.

**Comment by shockdude** [comment]
Imo chorus should use a license more copyleft than ISC, to ensure that the source code remains open, like [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/) or similar.

**Comment by Paturages** [comment]
GPLv3 it is.
