### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by thefreshlycutgrass** [Paturages/chorus#218]
Every time I try to go to chorus, it either:

A: Gives me a bad gateway screen
B: Says there are no songs in the database

**Comment by Paturages** [comment]
The (home) server I'm hosting this on likes to go down whenever: when it gets fixed depends on when I'm able to get home and reboot the thing.

Right now it's back up, but I'll keep the issue around because I need to migrate the thing to another thing.

**Comment by Paturages** [comment]
Closing this: chorus has effectively been migrated to a DigitalOcean droplet.
