### ISSUE TITLE
Search by Chart Checksum

### ISSUE THREAD

**Issue by kj800x** [Paturages/chorus#225]
Since CH stores the song score data using the chart checksum, it would be great if there was a way to search chorus for a chart given the checksum. Chorus already stores this checksum data for each chart. Currently it doesn't use that field for determining search results (AFAICT).

For example, `c1c0cf3fa09fe036f75e8d60524edb4d` is the checksum for Grim Birthday's chart of Something Human (the first result on https://chorus.fightthe.pw/search?query=Something%20Human), but when I search for that checksum, Something Human isn't even in the results (https://chorus.fightthe.pw/search?query=c1c0cf3fa09fe036f75e8d60524edb4d). This could probably be a search factor that either matches or doesn't match (We probably wouldn't need Something Human to be a result if the user searches for a substring of the hash, eg: `8d60524`).

Related to #23, but that issue is for grouping the charts, whereas this would be to show the charts when the checksum is searched for.

**Comment by Paturages** [comment]
The search entry `md5=c1c0cf3fa09fe036f75e8d60524edb4d` now only yields the results matching the provided checksum. It can either be entered in this format in the search bar, or pasted in the "MD5 checksum" field in "advanced search".
