### ISSUE TITLE
download button not working

### ISSUE THREAD

**Issue by DerpyMcderpster** [Paturages/chorus#230]
whenever I try to download a song, instead of the google drive or the pop up coming up, it says that the server isn't responding with a bullshit explaination from Cloudfare. WTF?!
![screenshot 3](https://user-images.githubusercontent.com/45465767/49241139-9e544180-f3cc-11e8-80cc-72b601e14cfd.png)

**Comment by Paturages** [comment]
This was a specific issue with `public.fightthe.pw` download links: since my Internet was down yesterday, these links were also down (and chorus as a whole was also down for a while). Everything should be operational now, feel free to re-open this ticket if you still have issues.
