### ISSUE TITLE
Clone Hero keys

### ISSUE THREAD

**Issue by 1BrotherZombies2** [Paturages/chorus#240]
Hello there,
I'm Tân, I'm Vietnamese => I don't have much money => I don't want to use money to buy a guitar for clone hero. So, I put the keys like this: 1,2,3,4,5, arrow up and arrows down.
For some reasons, I can't press 4,5 and another key. I can't do these combos:
1,4,5    2,4,5    3,4,5
Please help, I've tried 3 different keyboards and it's still not working.
Yours clone hero,
Tân
Ps: I'm vietnamese => Not the best at English

**Comment by Paturages** [comment]
Hey,

First of all, this is not a Clone Hero help line: this is about chorus, a project separate from Clone Hero. I'll advise you refer to the official [Discord server](https://discord.gg/Hsn4Cgu) for future help.

I'll however paste the information you need here:
> No, what you are experiencing is not a bug. The reason you can't press more than a few keys and have them register in-game is called "Keyboard Ghosting." The only fixes are either rebinding keys in hopes you keyboard will register them, or buying an anti-ghosting keyboard. Learn more from https://youtu.be/kOkV9BalNcw
Test your keyboard here: https://v6p9d9t4.ssl.hwcdn.net/html/131423/index.html

**Comment by 1BrotherZombies2** [comment]
Thank you and super sorry this.
