### ISSUE TITLE
Master of puppets

### ISSUE THREAD

**Issue by zizap445** [Paturages/chorus#245]
https://mega.nz/#F!wh51FARC!GTuk8g_2j1rmvKmoGSIv2g

**Comment by Paturages** [comment]
Oh yeah, no that's not how you submit a song unfortunately:
* chorus doesn't support MEGA just yet
* [it requires a folder containing 10 charts of acceptable quality as stated here](https://github.com/Paturages/chorus/blob/master/sources/sources.txt)
* either do a modification and a pull request on that file, or DM me `Paturages#9405` whenever you get your 10 charts together
