### ISSUE TITLE
Query by ID

### ISSUE THREAD

**Issue by TrentWest7190** [Paturages/chorus#257]
I'm currently working on building a chart downloader/manager using Chorus, and I'd like to be able to query on a chart's specific ID.

**Comment by Paturages** [comment]
You might want to use the checksum of the chart as an identifier (`song.hashes.file`): you can query a chart with a particular MD5 checksum like this:
https://chorus.fightthe.pw/api/search?query=md5=6620119b42aec99d2e9e10620293e1de
(this should yield only "Spear Thrower")
