### ISSUE TITLE
Rush song problem

### ISSUE THREAD

**Issue by ChristianWalker** [Paturages/chorus#260]
I'm trying to download some Rush songs, but whenever I try it says I can't connect even though I'm connected to the internet and there are no other problems. Some songs are ok to download but it seems Neversoft's and Harmonix's charts are the specific ones I can't, and they're the only charters I can see.

**Comment by Paturages** [comment]
My power was out until now, which caused songs not hosted on Google Drive to not work. It should be operational now!

Sorry for the inconvenience.
