### ISSUE TITLE
RockGamer

### ISSUE THREAD

**Issue by Elihuc127** [Paturages/chorus#261]
Why doesn't a single link from RockGamers content of RockBandNetwork songs work?

Edit: Nothing from RockBandNetwork titled songs have a link that works. it just says "Waiting for something to respond..." I own a Acer Nitro 5 Gaming Laptop with 1 Gig of internet and no internet issues even.... except this. Am I missing something here?

Edit x2: Songs I search for are He Sleeps in a Grove (Amberian Dawn) and Pandemonium (Chaotrope)

**Comment by Paturages** [comment]
My power was out until now, which caused songs not hosted on Google Drive to not work. It should be operational now!

Sorry for the inconvenience.

**Comment by Elihuc127** [comment]
JUST GRABBED EVERYTHING THANK YOU!!!!!!! (Just in case your power disappears again…)

Sent from Mail for Windows 10

**Comment by Elihuc127** [comment]
On the google drive page to download stuff, im getting a notification saying “Download quota exceeded for this file, so you cant download it at this time” How do I get around that?


Sent from Mail for Windows 10

**Comment by Paturages** [comment]
![image](https://user-images.githubusercontent.com/9801350/57185532-70b87a80-6ecd-11e9-9ff6-f9d069c124a3.png)
Adding to your drive might do it
