### ISSUE TITLE
Miles - Electronic Boutique: update charter to HaleyHalcyon

### ISSUE THREAD

**Issue by JapanYoshi** [Paturages/chorus#285]
Hi, this is HaleyHalcyon looking herself up on Chorus like a f***ing loser. Could you correct the charter of Miles - Electronic Boutique from Akira Sora (old alias) to HaleyHalcyon (current alias as of Anti Hero 2)? Thanks!

P.S. What do you think of changing the charter names on my older charts as "Akira Sora"?

**Comment by Paturages** [comment]
Hey there,

[The charts](https://chorus.fightthe.pw/search?query=charter%3D%22akira%20so%22) currently labeled as "Akira Sora" are of the responsibility of Squirrel and Siavash for the AH2 drive. I'd suggest talking to them about it.
