### ISSUE TITLE
Chorus Website Download Issues

### ISSUE THREAD

**Issue by TheQuackiestStrats** [Paturages/chorus#289]
On the Chorus website, if a song link takes me to a Google Drive download, I can download the ZIP file without an issue. If the link opens a new tab and has me download it (whether I am on Chrome or Firefox), it will say it finished downloading but wont download any data. All files are 0KB and are un-readable.

**Comment by Paturages** [comment]
related to #286 ; see [this message](https://github.com/Paturages/chorus/issues/286#issuecomment-530736218)
