### ISSUE TITLE
Some popular songs dont have working links.

### ISSUE THREAD

**Issue by briankung114** [Paturages/chorus#293]
Some examples:
https://public.fightthe.pw/ghrb/Guitar%20Hero%20Live/Skrillex%20-%20Bangarang.zip
https://public.fightthe.pw/rehosts/rb4Bruno%20Mars%20-%2024K%20Magic.zip

**Comment by Paturages** [comment]
if there are still some remaining public.fightthe.pw urls, just keep in mind that replacing
https://public.fightthe.pw/ghrb/ by http://ghrb.fightthe.pw/ and
https://public.fightthe.pw/rehosts by http://rehosts.fightthe.pw/
will get you around

that's the workaround for now
