### ISSUE TITLE
Broken Chart

### ISSUE THREAD

**Issue by 7SJN** [Paturages/chorus#303]
XEntombmentX's chart for I Prevail's "Bow Down" is broken and does not play

**Comment by Paturages** [comment]
I am not responsible of the charts and songs that are indexed by chorus (except the charts that are attributed to "Paturages"). If you have an issue with any of those, please contact the charters and/or the source owners.

I've however linked this issue directly to XEntombmentX, but you should preferably conduct this report directly to him in Discord DMs.
