### ISSUE TITLE
Api count is way off. Used to be 25k+ shows only 5k songs.

### ISSUE THREAD

**Issue by goofedup** [Paturages/chorus#306]
I scrape the data occasionally to obtain an artist list and to see if there's anything new I'd like to play. My last scrape about a month or so ago came up with 25k songs. I tried today and only 5k songs were found. I checked http://chorus.fightthe.pw/api/count and noticed the error.

Hope this is fixed soon as Chorus provides me with much entertainment! Would love if an artist list or selection was added to the site eventually!

**Comment by Paturages** [comment]
currently rescanning back to the original song count, it's gonna take a while...

**Comment by Paturages** [comment]
Currently fixed to some extent, more metadata might be recovered as the days go on.
