### ISSUE TITLE
The Rock Band Links are down!

### ISSUE THREAD

**Issue by JohnSmith2007** [Paturages/chorus#307]
https://drive.google.com/drive/folders/1GgPj9Pg-vmB_1xTUoccyma2cxmDKwhjm
this leads to a 404. This needs to be fixed ASAP!

**Comment by Paturages** [comment]
https://github.com/Paturages/chorus/commit/16cfe2c046fa6cf6fc0a3081e4fce50b0403998c#diff-8670de0b82c65bbbacb814dbdc595b60R372

The RB source has been fixed to point to the right drive, as the maintainers had some takedown troubles. We might see the songs appear again in the next few days.
