### ISSUE TITLE
searching something and results in showing nothing related to what I searched

### ISSUE THREAD

**Issue by g00ssss** [Paturages/chorus#308]
Hello! Ive been recently having issues with chorus that issue being that when I search for a exact song I dont get the exact thing I search for example being I search up "Motley Crue" it gives me one result and I know that people charted Motley Crue more than once besides the one song thats actually by them, the other songs in the results are "Sugar honey ice and tea" by Bring me to Horizon and "Lights out" by Royal Blood. Which doesnt make any sence because im not searching for that.

Please figure this out THANKS!

**Comment by xal3xhx** [comment]
my search is working just fine, if you are still having the issue try clearing your cookies and try again

**Comment by Ahriana** [comment]
in your specific case 'Motley Crue' is not their name, 'Mötley Crüe' is. you will have to use the correct search terms

**Comment by Paturages** [comment]
solved to some extent by not using that weird similarity postgres query thing by default
