### ISSUE TITLE
Instrument icon url malformed

### ISSUE THREAD

**Issue by Ghoelian** [Paturages/chorus#310]
The website seems to try to get the instrument icons from https://chorus.fightthe.pw/[object%20Module]. I'm assuming the [object%20Module] is a missing JSON.stringify().
![image](https://user-images.githubusercontent.com/33285224/90958098-5162a980-e492-11ea-8707-314d86e59da0.png)
![image](https://user-images.githubusercontent.com/33285224/90958114-663f3d00-e492-11ea-8e8f-ad5c2f4a7423.png)
![image](https://user-images.githubusercontent.com/33285224/90958124-72c39580-e492-11ea-96bf-0c192b2a486e.png)

**Comment by Ahriana** [comment]
JSON.stringify would show as `[native code]` this looks like a bad require or something similar form the server templating function

after looking i might be right:
https://github.com/Paturages/chorus/blob/293f36e422ea52b74bd5d60a51f6d0080578caf4/src/app/components/molecules/DifficultyMeter/index.jsx#L5

nothing jumps out to me instantly so possibly missing image or something around that, not too sure

**Comment by Paturages** [comment]
here's the fix: https://github.com/Paturages/chorus/commit/a309600aea9ac1daac831e5583460429e407f9d7

likely a side-effect of randomly bumping dependencies whoops

**Comment by Ghoelian** [comment]
It looks like the entire thing is now missing. Is this intended?
![image](https://user-images.githubusercontent.com/33285224/92135849-93cda400-ee0b-11ea-9cea-86cf10697f3b.png)

**Comment by Paturages** [comment]
This is a separate issue due to failure grabbing relevant metadata from those charts, but the ones that do have metadata are fixed now.
