### ISSUE TITLE
Schmutz06 Marathon chart - broken link

### ISSUE THREAD

**Issue by matrefeytontias** [Paturages/chorus#314]
When you search for this song, you get this : https://chorus.fightthe.pw/search?query=marathon%20schmutz06

The second link is missing a slash in the URL
Broken (current) : http://rehosts.fightthe.pw/schmutzSchmutz06%20-%20Marathon.zip
Fixed : http://rehosts.fightthe.pw/schmutz/Schmutz06%20-%20Marathon.zip

**Comment by Paturages** [comment]
rehosts are now reuploaded elsewhere
