### ISSUE TITLE
Cannot download packs from the spreadsheet

### ISSUE THREAD

**Issue by kalvinmerr** [Paturages/chorus#319]
Hello,

I cannot download certain guitar hero packs from the excel sheet, When I try to I get this error:
-GH metallica, GH Metallcia DLC, Band Hero, GH Live, Van Halen, Warriors of Rock, Smash hits

Sorry, you can't view or download this file at this time.

Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator.

Thank you,

**Comment by Paturages** [comment]
I'm not responsible of the spreadsheet, please direct your complaints to the [ch discord](https://discord.gg/Hsn4Cgu)

also probably just read the error
