### ISSUE TITLE
My anti malware detected a trojan in one of Zantor's charts

### ISSUE THREAD

**Issue by zemphys** [Paturages/chorus#321]
As stated above, I downloaded a chart by Zantor who I believed was a reputable creator. I've downloaded many of his tracks off of chorus and never had any issues. Here's a screenshot of what I saw. Sorry if this is wrong, but it's definitely alarming for me.
![zantor](https://user-images.githubusercontent.com/80984660/111836490-c2552d00-88cc-11eb-9615-1886ba4e969f.jpg)

**Comment by Paturages** [comment]
this is most likely a false positive, as google drive has its own antivirus contraption; I dl'ed and scanned it myself just to be sure but nothing was detected.

Other searches on reddit for "oneeva" seems to follow the false positive hypothesis as well
