### ISSUE TITLE
Can't look for technical death metal songs.

### ISSUE THREAD

**Issue by GDPixelShroom** [Paturages/chorus#322]
If I go over to advanced search, and look up any genre, it either loads some songs or doesn't load anything and says "Sorry, we couldn't find anything!". If I look up the genre "technical death metal" however, it keeps loading forever. Every other genre I tried looking up works fine tho.

**Comment by GDPixelShroom** [comment]
Not sure if this got fixed but it's working for me now, just wanted to update you.

**Comment by Paturages** [comment]
probably fixed by 6c7a2ef9813f0ac81b5b02d029ecdd5148992b6f
