### ISSUE TITLE
Cannot Search for a Band

### ISSUE THREAD

**Issue by graycar23** [Paturages/chorus#326]
This is a very weird problem, but I cannot search for the band Mastodon. I have tried through the regular search bar and the advanced search by setting the artist to Mastodon, and these both just lead to the website loading forever. I thought that the website might be down or something, but I am able to get randomizer results and search other things. Then I suspected that this is what the website does now when there are no results, so I wrote gibberish, but it brings up the normal "Sorry we couldn't find anything" message. This is the only band or search query that I have seen do this, but it is entirely possible there are more like it.
![Mastodon](https://user-images.githubusercontent.com/57331411/117036084-111b2280-acd3-11eb-8802-8bdad295330a.PNG)
![Metallica](https://user-images.githubusercontent.com/57331411/117036099-137d7c80-acd3-11eb-86f5-c02cdbc5afaa.PNG)
![Nothing](https://user-images.githubusercontent.com/57331411/117036102-15dfd680-acd3-11eb-956c-637f2614a4af.PNG)

**Comment by Paturages** [comment]
most likely fixed by 6c7a2ef9813f0ac81b5b02d029ecdd5148992b6f, reopen if not
