### ISSUE TITLE
Rebel Yell + Wind Cries Mary World Tour Charts will not convert

### ISSUE THREAD

**Issue by KinGod73** [Paturages/chorus#348]
Below error appears when trying to convert Rebel Yell and Wind Cries Mary Guitar Hero World Tour conversion charts to GHWOR files:

(OBSCURED PERSONAL FOLDER) used to cover my C drive details.

Rebel Yell:
ERROR! Lyric without a corresponding note at [42:2:000]
Context (innermost first):
  - shake: (OBSCURED PERSONAL FOLDER)/AppData/Local/Temp/1/onyx-8501a200a5a03e0b/gen/target/22640818/ghwor.note C:/Users/caldwe14/AppData/Local/Temp/1/onyx-8501a200a5a03e0b/gen/target/22640818/ghwor.qs
  - shake: (OBSCURED PERSONAL FOLDER)/AppData/Local/Temp/1/onyx-8501a200a5a03e0b/gen/target/22640818/ghwor.note
  - shake: (OBSCURED PERSONAL FOLDER)/AppData/Local/Temp/1/onyx-8501a200a5a03e0b/gen/target/22640818/song.pak.xen
  - shake: (OBSCURED PERSONAL FOLDER)/AppData/Local/Temp/1/onyx-8501a200a5a03e0b/gen/target/22640818/ghworlive

The Wind Cries Mary:
ERROR! Lyric without a corresponding note at [17:3:120]
Context (innermost first):
  - shake: (OBSCURED PERSONAL FOLDER)/AppData/Local/Temp/1/onyx-ddae0315c58740c4/gen/target/22640818/ghwor.note C:/Users/caldwe14/AppData/Local/Temp/1/onyx-ddae0315c58740c4/gen/target/22640818/ghwor.qs
  - shake: (OBSCURED PERSONAL FOLDER)/AppData/Local/Temp/1/onyx-ddae0315c58740c4/gen/target/22640818/ghwor.note
  - shake: (OBSCURED PERSONAL FOLDER)/AppData/Local/Temp/1/onyx-ddae0315c58740c4/gen/target/22640818/song.pak.xen
  - shake: (OBSCURED PERSONAL FOLDER)4/AppData/Local/Temp/1/onyx-ddae0315c58740c4/gen/target/22640818/ghworlive

**Comment by Paturages** [comment]
sir this is a walmart

(I have nothing to do with this)
