### ISSUE TITLE
Single quote causing issues in search

### ISSUE THREAD

**Issue by teeejw** [Paturages/chorus#351]
Searching for "Guns N' Roses" returns no results. Searching for "Guns N Roses" (with no quote character) returns the results you would expect from the first search.

Also, I know this isn't really the proper forum, but I love what you've built. Keep up the good work!

**Comment by Paturages** [comment]
seemingly fixed by https://github.com/Paturages/chorus/commit/e8a849f60e68c384ac4a6f72de1705d84b7a233c

thanks for the kind words
