### ISSUE TITLE
Chart curation system

### ISSUE THREAD

**Issue by Paturages** [Paturages/chorus#38]
As charters and chart reviewers, quality control is one, if not the main focus point for the rhythm gaming community. The idea is to reward and promote people who are putting real effort into making their stuff *good*.

* **Discord login**: to let charters and/or chart reviewers manually curate, moderate and review charts. Consider opening up reviews for non-charters to a lesser extent (anonymous /5 rating).
* **Charters highlighting**: Add fancy colors to charter names according to an internal whitelist (that will eventually be tied to CH Discord roles). Possibly add bias towards more skilled charters in the search results.

**Comment by clxxiii** [comment]
I don't know about this one. 


     Sure, it would benefit those who have been with the community since the beginning. Give benefits to those who help keep the community alive. because, without charts, there is no game. So many people are behind helping this game thrive, and by implementing this system, it might make it die out quicker.

     As a relatively unknown charter, this would severely impact not only my morale but make aspiring charter's lives even more difficult. I have several charts on Chorus that other, more popular charters have made their own version of. It's hard enough as of now to get people to play your stuff without stream hopping, and even then people tend to download the wrong chart. Name Highlighting would make that even more of a nightmare. There is already a standard to get your charts on Chorus, why does there need to be a second one? 

     Think osu! ranking. You have to not only work your ass off to get a map ranked but also get lucky to get people to see it. There are so many unranked maps that are truly stellar, They just didn't get lucky. I fear that the same would happen if we had highlighted names. 

     The charting community as of right now is pretty small. If it grows, anyone that doesn't have a highlighted name is, intentional or not, getting discriminated upon. It's a giant "I'm an unskilled charter. Don't play my chart" sign. 

     Instead of honoring those who make incredible charts, we should honor the charts themselves. No matter how experienced you are, you can still make a subpar chart. Everyone needs to get out a shitpost every now and then. If highlighted names are used, then those shitposts are highlighted too.

Do all the smaller charters a favor, and help them become great, instead of diminishing them from creating more.

**Comment by Paturages** [comment]
@clxxiii Several points:
This is a pretty old ticket and I do have slightly more insight regarding chart curation. Notably, the "charters highlighting" part has been enforced (albeit manually) for a good while now.

The fact that there are 2 levels of standards: chorus without role and chorus with role if anything makes it easier on smaller, but promising charters. Nowadays, [due to time and motivation constraints](https://github.com/Paturages/chorus/blob/master/sources/sources.txt#L3), I purely rely on the charter role application system as an inflow of new charters, instead of reviewing them myself: if they don't fit the standards of the charter role (which are some of the highest in the rhythm game community and really challenging to get without extensive musical knowledge) but are promising and decent nonetheless, getting on chorus without a "blue name" would be a consolation prize.

The ultimately intended system is: getting on chorus is already a privilege in and of itself, getting the "blue name" (which comes with the CH Discord charter role) is another achievement and goal as a charter. We want to incentivize and encourage charters to provide standards compliant and good content. Well, to be honest, it's mostly for the perk of filtering out bad, low effort content, which has also been a longstanding issue in the GH/RB/CH customs community as a whole, and a pain point as a player. Though in practice, the reputation may be closer to what you describe, with non-roled charters being segregated, but at least they have a chance to get their foot in the door.

It also doesn't help that the GH/RB/CH customs community has drastically different standards than the osu! ones: many of osu!'s curation ideas and features wouldn't work well if at all in our community, or the ones that *would* work well would require too much time and effort that I can't afford to put into the platform. I'm however in contact with a few developers in the community who may be able to put said time and effort, notably one who has extensive osu! community experience, so it's most likely not out of the table yet.

People should also be aware that chorus is not the only platform available to spread your charting output, and definitely should not be the only one. I think a vast majority of charters, if not all of them, have gotten big mainly by interacting with the community, notably through the exchange of feedback. Interactive media such as the main CH Discord (#charting-feedback, #charting-general), streams, applying for the charter role (which gives you, worst case scenario, detailed feedback on ho to improve your charts to provide a better player experience), trying your hand in the CSC monthly packs as a guest, and so on, should give you the full and intended experience you have to go through as a charter.

Ending word and tl;dr: while I would love to get smaller *promising* charters get their word out, I don't have the time and bandwidth anymore to do so. The emphasis on "promising" is because a lot of us don't want to see the charting scene going to shit because we opened the floodgates, but we also don't want it to die because we tightened the gates too much. Unfortunately, the middle ground happens to be the state we're in, and improving the overall charter experience without compromising on quality standards is still a long ways away, but it's what I will strive for, with the few time that I have.

**Comment by Paturages** [comment]
2 years and some later, I'm now a project loved captain on osu!mania lol, there's the same amount or at least intent in content curation especially for tournament files and loved candidates

well that was a good throwback: this is now solved by keeping an independent stream of applications for chorus, thanks to a bunch of benevolent chorus reviewers. Godspeed.
